package seng201.team0.unittests.services; // Assuming services package, adjust if models

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import seng201.team0.models.*;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class RaceTest {

    private Course testCourse;
    private Route testRoute;
    private Difficulty testDifficulty;
    private Race race;

    @BeforeEach
    void setUp() {
        testCourse = Course.DESERT; // NumberOfOpponents = 4
        testRoute = Route.DESERT_DRIFT; // Base opponentSpeed = 0.8
        testDifficulty = Difficulty.EASY;
        // Constructor generates opponents based on course's opponent count and route's base speed
        race = new Race(testCourse, testRoute, testDifficulty);
    }

    @Test
    void constructorSetsPropertiesAndGeneratesOpponents() {
        assertEquals(testCourse, race.getCourse());
        assertEquals(testRoute, race.getRoute());
        assertEquals(testDifficulty, race.getDifficulty());
        assertNotNull(race.getOpponents());

        // DESERT course has 4 opponents. DESERT_DRIFT generates them.
        assertEquals(testCourse.getNumberOfOpponents(), race.getOpponents().size());

        // Check opponent speeds generated by Route.DESERT_DRIFT.generateOpponents()
        // Route.DESERT_DRIFT has base opponentSpeed 0.8
        // Speeds should be 0.8, 0.9, 1.0, 1.1 for 4 opponents
        List<OpponentCar> generatedOpponents = race.getOpponents();
        double expectedBaseSpeed = 0.8; // from Route.DESERT_DRIFT
        for (int i = 0; i < generatedOpponents.size(); i++) {
            double expectedSpeed = expectedBaseSpeed + (i * 0.1);
            assertEquals(expectedSpeed, generatedOpponents.get(i).getSpeed(), 0.001, "Opponent " + i + " speed mismatch");
        }
    }

    @Test
    void getCourseReturnsCorrectCourse() {
        assertEquals(testCourse, race.getCourse());
    }

    @Test
    void getRouteReturnsCorrectRoute() {
        assertEquals(testRoute, race.getRoute());
    }

    @Test
    void getOpponentsReturnsCorrectList() {
        assertNotNull(race.getOpponents());
        assertEquals(testCourse.getNumberOfOpponents(), race.getOpponents().size());
    }

    @Test
    void getDifficultyReturnsCorrectDifficulty() {
        assertEquals(testDifficulty, race.getDifficulty());
    }

    @Test
    void setRouteChangesRoute() {
        Route newRoute = Route.DESERT_LONG;
        race.setRoute(newRoute);
        assertEquals(newRoute, race.getRoute());
        // Note: Setting route does not regenerate opponents in the current Race implementation.
        // The original opponent list (based on old route/course combo) remains. This test confirms that.
        assertEquals(testCourse.getNumberOfOpponents(), race.getOpponents().size()); // Opponent count shouldn't change just by setRoute
    }

    @Test
    void setCourseChangesCourse() {
        Course newCourse = Course.MOUNTAIN; // Mountain has 3 opponents
        race.setCourse(newCourse);
        assertEquals(newCourse, race.getCourse());
        // Note: Setting course also does not regenerate opponents or update their count
        // to match the new course's opponent number in the current Race implementation.
        assertNotEquals(newCourse.getNumberOfOpponents(), race.getOpponents().size()); // Original opponent count from DESERT remains
        assertEquals(testCourse.getNumberOfOpponents(), race.getOpponents().size());
    }

    @Test
    void setOpponentsChangesOpponentsList() {
        List<OpponentCar> newOpponents = new ArrayList<>();
        newOpponents.add(new OpponentCar(1.0));
        newOpponents.add(new OpponentCar(1.2));
        race.setOpponents(newOpponents);
        assertEquals(newOpponents, race.getOpponents());
        assertEquals(2, race.getOpponents().size());
    }

    @Test
    void toStringFormatsCorrectly() {
        String expectedString = testCourse.getName() + " - " + testRoute.getRouteName();
        assertEquals(expectedString, race.toString());

        Course cityCourse = Course.CITY;
        Route cityRoute = Route.CITY_ALLEYS;
        Race cityRace = new Race(cityCourse, cityRoute, Difficulty.HARD);
        String cityExpectedString = cityCourse.getName() + " - " + cityRoute.getRouteName();
        assertEquals(cityExpectedString, cityRace.toString());
    }
}